fmha v3 API only generate for supported targeting GPU arch
Refactor to resolve the building issue for gfx940, and also fix symbol not found if "gfx942" or "gfx950" is not the targeting compiling GPU arch:

```log
  In file included from TransformerEngine/build/cmake/ck_fused_attn/gen_src/mha_bwd.cpp:1:
  In file included from TransformerEngine/transformer_engine/common/ck_fused_attn/../../../3rdparty/aiter/csrc/include/mha_bwd.h:7:
  TransformerEngine/transformer_engine/common/ck_fused_attn/../../../3rdparty/aiter/csrc/include/aiter_hip_common.h:147:5: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
    147 |     hipGetDeviceProperties(&prop, 0);
        |     ^~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~
  /appl/lumi/SW/CrayEnv/EB/rocm/6.2.2/include/hip/hip_runtime_api.h:91:32: note: expanded from macro 'hipGetDeviceProperties'
     91 | #define hipGetDeviceProperties hipGetDevicePropertiesR0600
        |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  TransformerEngine/build/cmake/ck_fused_attn/gen_src/mha_bwd.cpp:69:9: error: use of undeclared identifier 'gfx90a'
     69 |     t = gfx90a::fmha_bwd_v3(traits, args, stream_config, seqlen_q_padded, seqlen_k_padded, is_v3_api_check);
        |         ^
  1 warning and 1 error generated when compiling for gfx90a.
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>